name: SmartClubs
version: '${project.version}'
main: com.zygro.smartclubs.SmartClubs
api-version: 1.19
authors: [Zygro]
description: Custom player groups for your Spigot server.

commands:
  test:
    description: Tests the commands out
    usage: /<command>
  typecreate:
    description: Creates new group types.
    usage: /<command> <name>
    aliases: [tcreate]
  groupcreate:
    description: Creates new groups.
    usage: /<command> <type> <name>
    aliases: [gcreate]