name: SmartClubs
version: '${project.version}'
main: smartclubs.SmartClubs
api-version: 1.19
authors: [Zygro]
description: Custom player groups for your Spigot server.

commands:
  smartclubs:
    description: SmartClubs admin commands.
    usage: /<command> [arguments]
    aliases: [sc]
  typecreate:
    description: Creates new group types.
    usage: /<command> <name>
    aliases: [tcreate]
  groupcreate:
    description: Creates new groups.
    usage: /<command> <type> <name>
    aliases: [gcreate]
  groupjoin:
    description: Joins groups.
    usage: /<command> <type> <name>
    aliases: [gjoin]
  groupmanage:
    description: Lets you manage your groups.
    usage: /<command> <type-name>
    aliases: [gmanage]